project:
  type: website
  output-dir: docs
  preview:
    port: 4200

website:
  title: "Command Line Algorithmic Music System (CLAMS)"
  site-url: "https://algocompsynth.github.io/CLAMS-Blog"
  navbar:
    right:
      - about-CLAMS.qmd
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/AlgoCompSynth/CLAMS
      - icon: mastodon
        href: https://ravenation.club/@AlgoCompSynth
      - icon: linkedin
        href: https://www.linkedin.com/in/znmeb/
format:
  html:
    theme: darkly
    css: styles.css

editor: visual

