project:
  type: website
  output-dir: docs
  preview:
    port: 4200

website:
  title: "Command Line Algorithmic Music System (CLAMS)"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: darkly
    css: styles.css

editor: visual

