---
title: "Welcome To the CLAMS Blog"
author: "M. Edward (Ed) Borasky"
date: "2023-02-12"
categories: [news, microcontrollers, live-coding, embedded-systems, forth, digital-signal-processing, algorithmic-composition, algorave, raspberry-pi-pico, zeptoforth]
filters:
  - social-share
share:
  permalink: "https://algocompsynth.github.io/CLAMS-Blog/posts/welcome/"
  description: "Welcome To the CLAMS Blog"
  twitter: false
  facebook: false
  reddit: false
  stumble: false
  tumblr: false
  linkedin: true
  email: false
  mastodon: true
---

Welcome to the [CLAMS](https://github.com/AlgoCompSynth/CLAMS "CLAMS on GitHub") blog! This is where I'll be thinking out loud about the project and sharing progress. There will be formal documentation as well, but I haven't gotten far enough into the project to lay that out in any great detail.

I'm not really looking for contributions at the moment, but if you have ideas that you think might be useful, see the [contributing guide](https://github.com/AlgoCompSynth/CLAMS/blob/main/CONTRIBUTING.md "CLAMS Contributing Guide"). This project is in its very early stages. I've been researching various components of what I want but the big one only clicked into place last week. If you want to chat, the best place to reach me online is [Mastodon](https://ravenation.club/@AlgoCompSynth "AlgoCompSynth by znmeb on Mastodon"). This blog does not have comments and never will.

There is a project board at <https://github.com/orgs/AlgoCompSynth/projects/8> if you want to follow along. The first order of business is to get the hardware set up and playing a 440 Hz sine wave - this is the "Hello, world" of micro-controller audio projects and the worst case is that CLAMS becomes another guitar tuner. I'll be posting pictures here, and maybe an MP3 of the audio.

At this point I believe my development host will be an Acer Chromebook Spin 714. Chromebooks have come a long way since Google gave me a developer preview of the original "Mario" Chromebook in late 2010. They run Android apps, Chrome web apps, and there's an integrated virtual machine that runs Debian "bullseye" in an LXD container.

I hope to have a minimum viable product to show by the middle of March. I at least need to have something that I can tweak by then because my other hobby, basketball analytics, will be kicking in with March Madness. ;-)
